import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/Button';
import Menu from '../components/Menu';
import { LinkIcon } from '@heroicons/react/24/solid';
import { TrashIcon } from '@heroicons/react/24/outline';
import Link from 'next/link';

const Home: NextPage = () => {
   return (
      <div className='container mx-auto'>
         <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <Menu />

         {/* <Header> */}
         <div className='flex justify-evenly py-36'>
            <div className='flex flex-col'>
               <h1 className='text-5xl font-bold mb-6'>
                  Ayo Mulai Voting! <br />
                  Saatnya giliran kamu
               </h1>
               <div className='space-x-3'>
                  <h2 className='text-lg inline-block rounded-md bg-zinc-100 px-3 py-1 mb-12'>
                     Web Voting No.1 Di Indonesia
                  </h2>
               </div>

               <div className='space-x-3'>
                  <Link href=''>
                     <Button text='Buat Vote Baru' className='font-semibold' />
                  </Link>
                  <Button
                     text='Ikutan Vote'
                     type='secondary'
                     className='font-semibold'
                  />
               </div>
            </div>

            <div className='pr-20'>
               <Image
                  alt={'Header'}
                  src={'/assets/header.svg'}
                  width={409}
                  height={357}
               />
            </div>
         </div>
         {/* </Header> */}

         {/* <Table> */}
         <div>
            <p className='py-5 text-lg font-semibold'>Vote yang saya buat</p>
            <table className='table-auto w-full border border-zinc-100'>
               <thead>
                  <tr className='border-b border-zinc-100'>
                     <th className='p-5 text-left'>No</th>
                     <th className='p-5 text-left'>Judul</th>
                     <th className='p-5 text-left'>Kandidat</th>
                     <th className='p-5 text-left'>Kode</th>
                     <th className='p-5 text-left'>Mulai</th>
                     <th className='p-5 text-left'>Selesai</th>
                     <th></th>
                  </tr>
               </thead>
               <tbody>
                  <tr>
                     <td className='p-5 text-left'>1</td>
                     <td className='p-5 text-left'>Pemilihan Organisasi</td>
                     <td className='p-5 text-left'>Budi VS Anto</td>
                     <td className='p-5 text-left'>POYTQW</td>
                     <td className='p-5 text-left'>20 Oct 2022 11:00 AM</td>
                     <td className='p-5 text-left'>22 Oct 2022 11:00 AM</td>
                     <td className='p-5 text-left'>
                        <div>
                           <Link href='#'>
                              <LinkIcon className='w-8 h-8 p-2 hover:bg-zinc-100 hover:rounded-md' />
                           </Link>
                           <Link href='#'>
                              <TrashIcon className='w-8 h-8 p-2 hover:bg-zinc-100 hover:rounded-md' />
                           </Link>
                        </div>
                     </td>
                  </tr>
               </tbody>
            </table>
         </div>
         {/* </Table> */}
      </div>
   );
};

export default Home;
